### ISSUE TITLE
Depend directly on Elemental2

### ISSUE THREAD

**Issue by dmg46664** [manolo/gwt-api-generator#77]
My problem is that because the existing`JsArray` is defined as `JsArray<T extends JavaScriptObject> extends JavaScriptObject`, it is enforcing too harsh a restriction the items stored in the array. I don't want to define my class as extending `JavaScriptObject` as this is a deprecated API and would prefer my `@JsType` annotated classes not to have all the restrictions imposed by the compiler.

I propose creating a `JsArrayNative` type that is included in this generator project which would work as an expected javascript array without any of the restrictions of `JsArray`. I didn't want to just go ahead and create this and submit a pull request if this is not the preferred approach of dealing with this. Obviously this would be a breaking API change to the generator.

What are your thoughts?

**Comment by manolo** [comment]
Well, since elemental2 preview is out, probably the next steps in the project would be get ride of temporary implementations in the project and use those. I have not taken a look to elemental2 but probably it does not have these problems.

**Comment by dmg46664** [comment]
@manolo  Thanks for the steer. I will take a look at what is on offer there. 

If nothing is available perhaps keeping the name `JsArray` with the same API and different package name to  minimize code breakage... but I am getting ahead of myself.

**Comment by dmg46664** [comment]
@manolo  - Nice! There is `elemental2.Array<T>` which looking superficially looks like it solves the problem 👍 

I used the following link to investigate: https://oss.sonatype.org/service/local/repositories/google-releases/content/com/google/gwt/elemental2-experimental/16-06-30/elemental2-experimental-16-06-30.jar

Will see if I can try and get it working with:

```
<dependency>
   <groupId>com.google.gwt</groupId>
   <artifactId>elemental2-experimental</artifactId>
   <version>16-06-30</version>
</dependency>
```

**Comment by manolo** [comment]
Good to know. Thanks for reporting. 
There is no so much documentation related with this, but you can take a look to this thread where elemental2 beta was announced https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/google-web-toolkit-contributors/MyGZ4-ASG-Y/PVuZvzwwDAAJ

**Comment by dmg46664** [comment]
Thanks again for setting me in the right direction.

**Comment by dmg46664** [comment]
Committing to branch https://github.com/dmg46664/gwt-api-generator/tree/elemental2.

**Comment by ibaca** [comment]
Are you sure that it is not enough to depend on jsinterop:base? using JsArrayLike for example?

**Comment by dmg46664** [comment]
@ibaca - No, I'm not sure and that's probably a better idea :-)

**Comment by dmg46664** [comment]
@ibaca - My test was to use the `gwt-api-generator` with [Vaadin's new grid 2.0](https://github.com/vaadin/gwt-polymer-elements/issues/149). I was only trying to hack it to get it working. It appears to work.

Obviously I haven't tested it with `JsArrayLike`. Presumably this would work fine provided you passed in an `Array` when expected. I guess ideally the generator would generate the most specific typed interface possible, in the case of the [grid stating specifically that an `Array` is required](https://github.com/vaadin/vaadin-grid/blob/45591c5137201a1ba88667b38998b4edf910538e/vaadin-grid-array-data-provider-behavior.html#L17) ?

**Comment by ibaca** [comment]
This seems to be solved! 👏
